<div class="recently-viewed clearfix container">
    <div class="row">
        <h2><?php echo $this->__('Recently Viewed') ?></h2>

        <div class="slider row">
            <div class="slide-control">
                <a class="recently-jcarousel-prev jcarousel-control" href="#"><i class="fa fa-angle-left"></i>Next</a>
                <a class="recently-jcarousel-next jcarousel-control" href="#"><i class="fa fa-angle-right"></i>Prev</a>
            </div>
            <div class="recently-jcarousel">
                <ol id="recently-viewed-items">
                    <li class="item" style="float: left">
                        <div class="recently-jcarousel-item">
                            <a href="#">
                                        <span class="product-image"><img
                                                src="<?php echo $this->getSkinUrl('images/sp.png'); ?>"
                                                alt="<?php echo $this->getSkinUrl('images/sp.png'); ?>"/></span>
                            </a>
                            <a href="#">
                                        <span class="product-name big">
                                            Product Name
                                        </span>
                                       <span class="product-name small">
                                            Product Name
                                        </span>
                            </a>
                            <span class="price">$19.95</span>
                        </div>
                    </li>
                    <li class="item" style="float: left">
                        <div class="recently-jcarousel-item">
                            <a href="#">
                                        <span class="product-image"><img
                                                src="<?php echo $this->getSkinUrl('images/sp.png'); ?>"
                                                alt="<?php echo $this->getSkinUrl('images/sp.png'); ?>"/></span>
                            </a>
                            <a href="#">
                                        <span class="product-name big">
                                            Product Name
                                        </span>
                                       <span class="product-name small">
                                            Product Name
                                        </span>
                            </a>
                            <span class="price">$19.95</span>
                        </div>
                    </li>
                    <li class="item" style="float: left">
                        <div class="recently-jcarousel-item">
                            <a href="#">
                                        <span class="product-image"><img
                                                src="<?php echo $this->getSkinUrl('images/sp.png'); ?>"
                                                alt="<?php echo $this->getSkinUrl('images/sp.png'); ?>"/></span>
                            </a>
                            <a href="#">
                                        <span class="product-name big">
                                            Product Name
                                        </span>
                                       <span class="product-name small">
                                            Product Name
                                        </span>
                            </a>
                            <span class="price">$19.95</span>
                        </div>
                    </li>
                    <li class="item" style="float: left">
                        <div class="recently-jcarousel-item">
                            <a href="#">
                                        <span class="product-image"><img
                                                src="<?php echo $this->getSkinUrl('images/sp.png'); ?>"
                                                alt="<?php echo $this->getSkinUrl('images/sp.png'); ?>"/></span>
                            </a>
                            <a href="#">
                                        <span class="product-name big">
                                            Product Name
                                        </span>
                                       <span class="product-name small">
                                            Product Name
                                        </span>
                            </a>
                            <span class="price">$19.95</span>
                        </div>
                    </li>
                    <li class="item" style="float: left">
                        <div class="recently-jcarousel-item">
                            <a href="#">
                                        <span class="product-image"><img
                                                src="<?php echo $this->getSkinUrl('images/sp.png'); ?>"
                                                alt="<?php echo $this->getSkinUrl('images/sp.png'); ?>"/></span>
                            </a>
                            <a href="#">
                                        <span class="product-name big">
                                            Product Name
                                        </span>
                                       <span class="product-name small">
                                            Product Name
                                        </span>
                            </a>
                            <span class="price">$19.95</span>
                        </div>
                    </li>
                    <li class="item" style="float: left">
                        <div class="recently-jcarousel-item">
                            <a href="#">
                                        <span class="product-image"><img
                                                src="<?php echo $this->getSkinUrl('images/sp.png'); ?>"
                                                alt="<?php echo $this->getSkinUrl('images/sp.png'); ?>"/></span>
                            </a>
                            <a href="#">
                                        <span class="product-name big">
                                            Product Name
                                        </span>
                                       <span class="product-name small">
                                            Product Name
                                        </span>
                            </a>
                            <span class="price">$19.95</span>
                        </div>
                    </li>
                    <li class="item" style="float: left">
                        <div class="recently-jcarousel-item">
                            <a href="#">
                                        <span class="product-image"><img
                                                src="<?php echo $this->getSkinUrl('images/sp.png'); ?>"
                                                alt="<?php echo $this->getSkinUrl('images/sp.png'); ?>"/></span>
                            </a>
                            <a href="#">
                                        <span class="product-name big">
                                            Product Name
                                        </span>
                                       <span class="product-name small">
                                            Product Name
                                        </span>
                            </a>
                            <span class="price">$19.95</span>
                        </div>
                    </li>
                    <li class="item" style="float: left">
                        <div class="recently-jcarousel-item">
                            <a href="#">
                                        <span class="product-image"><img
                                                src="<?php echo $this->getSkinUrl('images/sp.png'); ?>"
                                                alt="<?php echo $this->getSkinUrl('images/sp.png'); ?>"/></span>
                            </a>
                            <a href="#">
                                        <span class="product-name big">
                                            Product Name
                                        </span>
                                       <span class="product-name small">
                                            Product Name
                                        </span>
                            </a>
                            <span class="price">$19.95</span>
                        </div>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>